import localFont from "next/font/local";
import "./globals.css";
import { i18n } from "../../i18n-config";
import { getDictionary } from "../../get-dictionary";
import { DictionaryProvider } from "./components/DictionaryProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Alberto Ledesma Ollega - FULL STACK DEVELOPER",
  description: "Generated by Alberto Ledesma",
  icons: {
    icon: '/media/FOTOCV.jpg',
    apple: '/media/FOTOCV.jpg'
  }
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({ children, params }) {
  const dictionary = await getDictionary(params.lang);
  return (
    <html lang={params.lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <DictionaryProvider dictionary={dictionary}>{children}</DictionaryProvider>
      </body>
    </html>
  );
}